### ISSUE TITLE
Supercard DSTWO Plus

### ISSUE THREAD

**Issue by noX1609** [kitling/flashcart_core#10]
Hi,

is support for Supercard DSTwo Plus planned? Only read something about the normal DSTWO but nothing relating to the Plus version.
Would be gread if this would be possible :)

**Comment by dark-samus** [comment]
the commands should be similar, so if one is supported the other likely will be too. Kinda like ak2i hw 44/81 :P

**Comment by Valeri0p** [comment]
Aldo, @hedgeberg is working on it right now, you can follow his streams to see the progress ;)

**Comment by hedgeberg** [comment]
SuperCard ds2/2p support is something I am working on pretty heavily but it's a nasty piece of hardware to work with. At the moment we are not sure if we'll reach that finish line but we're hopeful. Ive been working on wrapping python around powerslaves to enable a full-on 3ds replay toolchain, since some of these commands are pretty clearly dependent on the state of the card, and this stuff is not well-documented enough at all.

**Comment by dark-samus** [comment]
I'm going to close this one, it's a "duplicate" (this one is the original, but the other has more pertinent information.)
