### ISSUE TITLE
R4 SDHC GOLD Pro Teal Time Save

### ISSUE THREAD

**Issue by NicknameGoesHere** [kitling/flashcart_core#25]
Will this card be supported?
![20170823_200042](https://user-images.githubusercontent.com/30986310/29644804-de0bf3c2-883e-11e7-8193-3a6fda88dc34.jpg)
![20170823_200314](https://user-images.githubusercontent.com/30986310/29644806-df590fb2-883e-11e7-899f-50a80012c8ac.jpg)
![20170823_200333](https://user-images.githubusercontent.com/30986310/29644807-e07c684e-883e-11e7-89aa-16558c8d3c20.jpg)
![20170823_200459](https://user-images.githubusercontent.com/30986310/29644808-e1ee7b04-883e-11e7-8806-ba884533beec.jpg)

**Comment by Juanito9001** [comment]
There was an issue of that flashcart, and the final report was that flashcart will no be compatible... right now... because the mode of work of that flashcart doesn't work with the injection metod of the ntrboot (something like that) 
Two options: 
1. Wait for support of that flashcart 
1. 2. Buy a compatible flashcart

All of this i know because i was tje creator  that issue

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dark-samus** [comment]
well, this flashcart was in another, now closed, issue. We can, in some way, support it, but it's kinda hacky and the PoC hasn't been finished yet. This card seems super common though. I'm going to close this issue, since it's a dupe and repoen the old issue since some new information has come to light.
