### ISSUE TITLE
R4 3DS UPGRADE SDHC [CLONE] (r4isdhc.com)

### ISSUE THREAD

**Issue by anuserlol** [kitling/flashcart_core#39]
ChipID: 00000000 
HW Revision: 00000000

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

- http://www.r4isdhc.com/wp-content/themes/nds9/images/s/5.jpg
 (Without www.r4isdhc.com on the pcb)

- http://www.r4isdhc.com/wp-content/themes/nds9/images/s/6.jpg

- http://www.r4isdhc.com/wp-content/themes/nds9/images/s/3.jpg
 (Without 2014 text on the front)

- http://www.r4isdhc.com/wp-content/themes/nds9/images/s/4.jpg
 (Without www.r4isdhc.com in the pcb)

</p></details> 

GM9 Untrimmed Dump: 
I can't provide becuase I don't have GM9 sorry.
</p></details> 
I can be a tester

**Comment by Juanito9001** [comment]
This anorher issue of this flashcart... well especifically of the flashcarts since 2014 to 2017

All of them are tha same everything.
Btw, the chipID reported of that models (2014 to 2017) is 000007C2
HwRev: 00000000 or someties is FFFFFFFF

_Enviado desde mi Samsung SM-G610M usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dark-samus** [comment]
Duplicate.
